services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: feedflow-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - mailpit
    networks:
      - feedflow

  nginx:
    image: nginx:alpine
    container_name: feedflow-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - feedflow

  db:
    image: mysql:8.0
    container_name: feedflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feedflow_dev
      MYSQL_USER: feedflow_user
      MYSQL_PASSWORD: feedflow2025
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - feedflow

  mailpit:
    image: axllent/mailpit:latest
    container_name: feedflow-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - feedflow

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: feedflow-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - feedflow

volumes:
  mysql-data:

networks:
  feedflow:
    driver: bridge
